@echo off
call npm install
echo Rendering 01_problem_gaps...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\01_problem_gaps.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\01_problem_gaps.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 02_objective_workflow...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\02_objective_workflow.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\02_objective_workflow.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 03_solution_pipeline...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\03_solution_pipeline.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\03_solution_pipeline.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 04_current_poc_architecture...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\04_current_poc_architecture.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\04_current_poc_architecture.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 05_edge_cloud_evolution...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\05_edge_cloud_evolution.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\05_edge_cloud_evolution.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 06_technical_implementation_table...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\06_technical_implementation_table.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\06_technical_implementation_table.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 07_novelty_integration...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\07_novelty_integration.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\07_novelty_integration.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 08_differentiation_handoffs...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\08_differentiation_handoffs.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\08_differentiation_handoffs.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 09_challenges_matrix...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\09_challenges_matrix.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\09_challenges_matrix.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 10_results_evidence...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\10_results_evidence.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\10_results_evidence.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 11_demo_storyboard...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\11_demo_storyboard.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\11_demo_storyboard.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 12_project_timeline...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\12_project_timeline.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\12_project_timeline.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 13_offline_sync_future...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\13_offline_sync_future.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\13_offline_sync_future.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 14_inspection_data_flow...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\14_inspection_data_flow.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\14_inspection_data_flow.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo Rendering 15_evidence_traceability...
call npx mmdc -i "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\source\15_evidence_traceability.mmd" -o "d:\Tata Innovent\Tata_Innovent-main\docs\presentation\assets\15_evidence_traceability.png" -c "mermaid_config.json" -p "puppeteer_config.json" -b white -s 4 --width 3000
echo ALL RENDERED!
